name: main
on:
  push:
    branches: [master, "8.0"]
  pull_request:
    branches: [master, "8.0"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x
      - name: Install FFmpeg - linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install ffmpeg -y
      - name: Build
        run: |
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test -c Release
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: nuget-packages
          path: |
            **/*.nupkg
          if-no-files-found: error
      - name: Codegen Build & Test
        if: matrix.os == 'windows-latest'
        run: |
          dotnet run -c Release -p FFmpeg.AutoGen.CppSharpUnsafeGenerator -- --input FFmpeg --namespace FFmpeg.AutoGen
          dotnet build FFmpeg.AutoGen
